package com.example.expensetracker

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.ui.graphics.vector.ImageVector

object IconUtils {
    val iconMap = mapOf(
        "ShoppingCart" to Icons.Default.ShoppingCart,
        "Restaurant" to Icons.Default.Restaurant,
        "DirectionsBus" to Icons.Default.DirectionsBus,
        "FlashlightOn" to Icons.Default.FlashlightOn,
        "Movie" to Icons.Default.Movie,
        "MedicalServices" to Icons.Default.MedicalServices,
        "School" to Icons.Default.School,
        "Work" to Icons.Default.Work,
        "AccountBalance" to Icons.Default.AccountBalance,
        "Home" to Icons.Default.Home,
        "FitnessCenter" to Icons.Default.FitnessCenter,
        "Fastfood" to Icons.Default.Fastfood,
        "LocalGasStation" to Icons.Default.LocalGasStation,
        "Flight" to Icons.Default.Flight,
        "Redeem" to Icons.Default.Redeem,
        "Payments" to Icons.Default.Payments,
        "ReceiptLong" to Icons.Default.ReceiptLong,
        "Category" to Icons.Default.Category,
        "Pets" to Icons.Default.Pets,
        "SportsEsports" to Icons.Default.SportsEsports,
        "DirectionsCar" to Icons.Default.DirectionsCar,
        "LocalMall" to Icons.Default.LocalMall,
        "RestaurantMenu" to Icons.Default.RestaurantMenu,
        "SelfCare" to Icons.Default.SelfImprovement,
        "Bolt" to Icons.Default.Bolt,
        "WaterDrop" to Icons.Default.WaterDrop,
        "Wifi" to Icons.Default.Wifi,
        "PhoneAndroid" to Icons.Default.PhoneAndroid,
        "Subscriptions" to Icons.Default.Subscriptions,
        "Build" to Icons.Default.Build,
        "Spa" to Icons.Default.Spa,
        "LocalCafe" to Icons.Default.LocalCafe,
        "LocalBar" to Icons.Default.LocalBar,
        "Apartment" to Icons.Default.Apartment,
        "LocalLaundryService" to Icons.Default.LocalLaundryService,
        "ChildCare" to Icons.Default.ChildCare,
        "Savings" to Icons.Default.Savings,
        "VolunteerActivism" to Icons.Default.VolunteerActivism,
        "MusicNote" to Icons.Default.MusicNote,
        "PhotoCamera" to Icons.Default.PhotoCamera,
        "Construction" to Icons.Default.Construction,
        "Chair" to Icons.Default.Chair,
        "MenuBook" to Icons.Default.MenuBook,
        "Handyman" to Icons.Default.Handyman,
        "Celebration" to Icons.Default.Celebration,
        "TheaterComedy" to Icons.Default.TheaterComedy,
        "Checkroom" to Icons.Default.Checkroom,
        "DryCleaning" to Icons.Default.DryCleaning,
        "DirectionsRun" to Icons.Default.DirectionsRun,
        "DirectionsBike" to Icons.Default.DirectionsBike,
        // Newly added icons
        "Store" to Icons.Default.Store,
        "HealthAndSafety" to Icons.Default.HealthAndSafety,
        "Devices" to Icons.Default.Devices,
        "CreditCard" to Icons.Default.CreditCard,
        "ShowChart" to Icons.Default.ShowChart,
        "LibraryBooks" to Icons.Default.LibraryBooks,
        "Palette" to Icons.Default.Palette,
        "ChildFriendly" to Icons.Default.ChildFriendly,
        "Yard" to Icons.Default.Yard,
        "Bed" to Icons.Default.Bed,
        "CleaningServices" to Icons.Default.CleaningServices,
        "Security" to Icons.Default.Security,
        "Newspaper" to Icons.Default.Newspaper,
        "Coffee" to Icons.Default.Coffee,
        "LunchDining" to Icons.Default.LunchDining,
        "LocalPizza" to Icons.Default.LocalPizza,
        "BakeryDining" to Icons.Default.BakeryDining,
        "Liquor" to Icons.Default.Liquor,
        "LocalPharmacy" to Icons.Default.LocalPharmacy,
        "LocalHospital" to Icons.Default.LocalHospital,
        "EvStation" to Icons.Default.EvStation,
        "CarRepair" to Icons.Default.CarRepair,
        "Public" to Icons.Default.Public,
        "Hotel" to Icons.Default.Hotel,
        "BeachAccess" to Icons.Default.BeachAccess,
        "MonetizationOn" to Icons.Default.MonetizationOn,
        "PieChart" to Icons.Default.PieChart,
        "SettingsBackupRestore" to Icons.Default.SettingsBackupRestore,
        "Storefront" to Icons.Default.Storefront,
        "CardGiftcard" to Icons.Default.CardGiftcard,
        "MoreHoriz" to Icons.Default.MoreHoriz,
        "Hardware" to Icons.Default.Hardware,
        "Commute" to Icons.Default.Commute,
        "Laptop" to Icons.Default.Laptop,
        "Tv" to Icons.Default.Tv,
        "Event" to Icons.Default.Event,
        "Policy" to Icons.Default.Policy,
        "Atm" to Icons.Default.Atm,
        "Description" to Icons.Default.Description,
        "Camera" to Icons.Default.Camera,
        "Gamepad" to Icons.Default.Gamepad,
        "LibraryMusic" to Icons.Default.LibraryMusic,
        "Language" to Icons.Default.Language,
        "Cloud" to Icons.Default.Cloud,
        "Smartphone" to Icons.Default.Smartphone,
        "Opacity" to Icons.Default.Opacity,
        "ElectricBolt" to Icons.Default.ElectricBolt,
        "SettingsSuggest" to Icons.Default.SettingsSuggest,
        "Favorite" to Icons.Default.Favorite,
        "SportsSoccer" to Icons.Default.SportsSoccer
    )

    fun getIcon(name: String?): ImageVector {
        return iconMap[name] ?: Icons.Default.Category
    }
}
